"""add card reconciliation tables

Revision ID: 5630518b2cff
Revises: e4a1f27c9d02
Create Date: 2026-08-28 15:09:37.996099

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5630518b2cff'
down_revision: str | None = 'e4a1f27c9d02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('matched_near_count', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_expense_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_card_reconciliations_project', 'card_reconciliations', ['project_id'], unique=False)
    op.create_table('card_reconciliation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('approved_on', sa.Date(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('merchant_biz_no', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('approval_no', sa.String(length=20), nullable=True),
    sa.Column('card_no_masked', sa.String(length=25), nullable=True),
    sa.Column('match_status', sa.Enum('MATCHED', 'MATCHED_NEAR', 'CANDIDATE', 'UNMATCHED', name='card_match_status'), nullable=False),
    sa.Column('matched_expense_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['card_reconciliations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_card_recon_lines_expense', 'card_reconciliation_lines', ['matched_expense_id'], unique=False)
    op.create_index('ix_card_recon_lines_recon', 'card_reconciliation_lines', ['reconciliation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_card_recon_lines_recon', table_name='card_reconciliation_lines')
    op.drop_index('ix_card_recon_lines_expense', table_name='card_reconciliation_lines')
    op.drop_table('card_reconciliation_lines')
    op.drop_index('ix_card_reconciliations_project', table_name='card_reconciliations')
    op.drop_table('card_reconciliations')
    # autogenerate가 빠뜨리는 부분: 테이블을 지워도 enum 타입은 남는다
    sa.Enum(name='card_match_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
