"""initial schema

Revision ID: c507a43441f4
Revises: 
Create Date: 2026-08-20 13:00:21.206156

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c507a43441f4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agency', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_date <= end_date', name='ck_projects_period'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('RESEARCHER', 'MANAGER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendor_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biz_no', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', 'UNREGISTERED', 'UNVERIFIED', name='vendor_status'), nullable=False),
    sa.Column('b_stt', sa.String(length=20), nullable=True),
    sa.Column('tax_type', sa.String(length=100), nullable=True),
    sa.Column('end_dt', sa.String(length=8), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_no')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('PERSONNEL', 'STUDENT_PERSONNEL', 'EQUIPMENT', 'MATERIAL', 'ACTIVITY', 'ALLOWANCE', 'OUTSOURCED_RND', 'INTL_JOINT_RND', 'INDIRECT', name='budget_category'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_budgets_amount_non_negative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'category', name='uq_budgets_project_category')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', name='report_status'), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_md', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_month BETWEEN 1 AND 12', name='ck_reports_month_range'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'period_year', 'period_month', name='uq_reports_period')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('PERSONNEL', 'STUDENT_PERSONNEL', 'EQUIPMENT', 'MATERIAL', 'ACTIVITY', 'ALLOWANCE', 'OUTSOURCED_RND', 'INTL_JOINT_RND', 'INDIRECT', name='budget_category'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_biz_no', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('spent_at', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'VALIDATING', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', name='expense_status'), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expenses_amount_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_created_by', 'expenses', ['created_by'], unique=False)
    op.create_index('ix_expenses_project_category_status', 'expenses', ['project_id', 'category', 'status'], unique=False)
    op.create_index('ix_expenses_project_status', 'expenses', ['project_id', 'status'], unique=False)
    op.create_index('ix_expenses_spent_at', 'expenses', ['spent_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', name='approval_action'), nullable=False),
    sa.Column('override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_expense_id'), 'approvals', ['expense_id'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('EXPENSE_PIPELINE', 'REPORT_GENERATION', name='automation_kind'), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='automation_status'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(expense_id IS NOT NULL)::int + (report_id IS NOT NULL)::int = 1', name='ck_automation_runs_single_target'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_automation_runs_status_id', 'automation_runs', ['status', 'id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_expense_id'), 'evidences', ['expense_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('DOC_EXTRACTION', 'CATEGORY_SUGGESTION', 'REPORT_NARRATIVE', name='ai_run_kind'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='ai_run_status'), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_category', sa.Enum('PERSONNEL', 'STUDENT_PERSONNEL', 'EQUIPMENT', 'MATERIAL', 'ACTIVITY', 'ALLOWANCE', 'OUTSOURCED_RND', 'INTL_JOINT_RND', 'INDIRECT', name='budget_category'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(expense_id IS NOT NULL) OR (report_id IS NOT NULL)', name='ck_ai_runs_has_target'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_ai_runs_confidence_range'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_expense_id'), 'ai_runs', ['expense_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_report_id'), 'ai_runs', ['report_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('rule_code', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Enum('PASS', 'INFO', 'WARN', 'FAIL', name='validation_severity'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_results_expense', 'validation_results', ['expense_id'], unique=False)
    op.create_index('ix_validation_results_rule_code', 'validation_results', ['rule_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validation_results_rule_code', table_name='validation_results')
    op.drop_index('ix_validation_results_expense', table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_ai_runs_report_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_expense_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_evidences_expense_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index('ix_automation_runs_status_id', table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index(op.f('ix_approvals_expense_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_expenses_spent_at', table_name='expenses')
    op.drop_index('ix_expenses_project_status', table_name='expenses')
    op.drop_index('ix_expenses_project_category_status', table_name='expenses')
    op.drop_index('ix_expenses_created_by', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('reports')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('budgets')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('vendor_checks')
    op.drop_table('users')
    op.drop_table('projects')
    # PG native enum 타입은 테이블 drop으로 사라지지 않으므로 명시적으로 정리한다
    for enum_name in (
        'ai_run_kind',
        'ai_run_status',
        'approval_action',
        'automation_kind',
        'automation_status',
        'budget_category',
        'expense_status',
        'project_status',
        'report_status',
        'user_role',
        'validation_severity',
        'vendor_status',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
